export const products = [
  {
    _id: '621235e59540445b3sdfe9s0',
    name: 'Amber Tea Owl Head',
    image: ['/images/yana-hurskaya-pot-1-a-unsplash.jpg', '/images/yana-hurskaya-pot-1-unsplash.jpg'],
    description:
      'This pottery is made of soft amber clay and glazed to a soft sheen. Beautiful enough to stand alone or as the perfect complement to your home decor, our Amber Tea Owl Head stand out in any setting. Eye catching with its unique flower headband and sure to be a conversation starter. ',
    color: 'Blanc ',
    category: 'Pot',
    material: 'Ceramic',
    price: 125.99,
    size: '19cm diameter, 20.5cm height',
    rating: 4,
    numReviews: 5,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: '636985e59540445b3c45e6af',
    name: 'Terracotta Bull',
    image: ['/images/yana-hurskaya-pot-2-a-unsplash.jpg', '/images/yana-hurskaya-pot-2-b-unsplash.jpg'],
    description:
      'A beautifully hand-crafted terracotta pottery bull. The piece is meticulously crafted from natural red clay and features a flower crown on the head. This terracotta bull will fill any space with a cozy and welcoming feel.With years of experience in handcrafting ceramics, our team has created this unique and one of a kind work of art to last you for a lifetime of memories.',
    color: 'Terra Cotta',
    category: 'Pot',
    material: 'Terracotta ',
    price: 120.0,
    size: '19cm diameter, 25.5cm height',
    rating: 3,
    numReviews: 15,
    isNew: false,

    reviews: [],
    stock: 5,
  },
  {
    _id: '6369860d9540445b3c45e6b1',
    name: 'Alabaster Textured Vase',
    image: ['/images/yana-hurskaya-pot-3-a-unsplash.jpg', '/images/yana-hurskaya-pot-3-b-unsplash.jpg'],
    description:
      'This beautiful alabaster vase is sure to be an eye-catching addition to your home.  Its bold style works in complementary or contrasting settings alike and is made to fit seamlessly into your home. Hand-glazed by skilled artisans, each alabaster vase is one-of-a-kind ',
    color: 'Warm White',
    category: 'Pot',
    material: 'Ceramic',
    price: 110.5,
    size: '23cm diameter, 35cm height',
    rating: 5,
    numReviews: 17,
    isNew: false,

    reviews: [],
    stock: 10,
  },
  {
    _id: '6369863c9540445b3c45e6b3',
    name: 'Volanic Glaze',
    image: ['/images/yana-hurskaya-pot-4-a-unsplash.jpg', '/images/yana-hurskaya-pot-4-b-unsplash.jpg'],
    description:
      'Volanic Glaze is a contemporary textured stoneware. The dark, rustic grey tones are perfect for both casual and formal styles of decor. Volanic glazes are hand-mixed at each firing, creating one-of-a-kind pieces that will last for years to come. This vase showcases intentional imperfections that add organic beauty to any spot in the home.',
    color: 'Acadia',
    category: 'Pot',
    material: 'Stoneware',
    price: 90.5,
    size: '15cm diameter, 25cm height',
    rating: 2,
    numReviews: 9,
    isNew: false,

    reviews: [],
    stock: 7,
  },
  {
    _id: '636986579540445b3c45e6b5',
    name: 'Facette White Vase',
    image: ['/images/kasia-sikorska-vase-1-a-unsplash.jpg', '/images/kasia-sikorska-vase-1-b-unsplash.jpg'],
    description:
      'Decorate your home with the Facette Vase. Its cylindrical shape features a narrow top and round base, allowing it to stand on any table or shelf. When filled with freshly cut flowers, it creates the perfect centerpiece for any decor..',
    color: 'Light Grey',
    category: 'Vase',
    material: 'Ceramic',
    price: 80.5,
    size: '12cm diameter, 20cm height',
    rating: 4,
    numReviews: 19,
    isNew: false,

    reviews: [],
    stock: 1,
  },
  {
    _id: '636986749540445b3c45e6b7',
    name: 'Craft Speckled Mug V1',
    image: ['/images/cafeconcetto-dinnerware-1-a-unsplash.jpg', '/images/cafeconcetto-dinnerware-1-b-unsplash.jpg'],
    description:
      'This Craft Speckled Mug is made from ceramic and has a warm white finish, with bone and tan speckles. It has a smooth texture that is textured on the inside and outside of the mug, making it perfect for any beverage including hot or cold coffee. Dishwasher- and microwave-safe. 10-oz. capacity',
    color: 'Bone',
    category: 'Dinnerware',
    material: 'Stoneware',
    price: 45.99,
    size: '8cm diameter, 10cm height',
    rating: 4,
    numReviews: 21,
    isNew: false,

    reviews: [],
    stock: 0,
  },
  {
    _id: '63804a5079636c2ced47757d',
    name: 'Craft Speckled Mug V2',
    image: ['/images/cafeconcetto-dinnerware-2-a-unsplash.jpg', '/images/cafeconcetto-dinnerware-2-b-unsplash.jpg'],
    description:
      'This Craft Speckled Mug was handmade from ceramic, and features a smooth textured surface with a dark brown speckle. A sibling of our Craft Speckled Mug V1, this one is a warm brown that hints at wood grain. Dishwasher- and microwave-safe. 10-oz. capacity',
    color: 'Warm Brown',
    category: 'Dinnerware',
    material: 'Stoneware',
    price: 45.99,
    size: '8cm diameter, 10cm height',
    rating: 4,
    numReviews: 7,
    isNew: true,

    reviews: [],
    stock: 12,
  },
  {
    _id: '6381275e8e8648e00b7c82f7',
    name: 'Silk Stoneware Salad Plate',
    image: [
      '/images/kasia-sikorska-II-dinnerware-3-a-unsplash.jpg',
      '/images/kasia-sikorska-II-dinnerware-3-b-unsplash.jpg',
    ],
    description:
      'Bring a touch of elegance to your food with this versatile, neutral-toned stoneware plate. The natural warmth of a silk finish on matted stoneware makes this dish a smart choice for both casual and formal dining occasions.',
    color: 'Silk',
    category: 'Dinnerware',
    material: 'Stoneware',
    price: 25.5,
    size: '18cm diameter, 1.8cm height',
    rating: 2,
    numReviews: 2,

    isNew: true,
    reviews: [],
    stock: 15,
  },
  {
    _id: '6381275e4e2345e00b7c82fj',
    name: 'Stella Bone Dinner Plate',
    image: [
      '/images/kasia-sikorska-II-dinnerware-4-a-unsplash.jpg',
      '/images/kasia-sikorska-II-dinnerware-4-b-unsplash.jpg',
    ],
    description:
      'Stella Bone Dinner Plate features a polished, bone-white glaze. Handpainted with a simple tinted green stripe around the edge. Stoneware is microwave safe and cleans up easily.',
    color: 'Bone',
    category: 'Dinnerware',
    material: 'Ceramic',
    price: 30.0,
    size: '25cm diameter, 1.8cm height',
    rating: 4,
    numReviews: 15,
    isNew: false,
    reviews: [],
    stock: 10,
  },
  {
    _id: '6385875e4e6975e00b7c91fj',
    name: 'Marin Coffee Mug Set',
    image: [
      '/images/mathilde-langevin-dinnerware-5a-unsplash.jpg',
      '/images/mathilde-langevin-dinnerware-5b-unsplash.jpg',
    ],
    description:
      'Enjoy a nice cup of coffee with this ceramic coffee mug and creamer set. Handpainted, the moon mists warm colour adds charm to any kitchen or dining table. The set is microwave safe, cleans up easily and looks great on display at home..',
    color: 'Moon Mist',
    category: 'Dinnerware',
    material: 'Ceramic',
    price: 55.0,
    size: '8cm diameter, 10cm height ',
    rating: 4,
    numReviews: 18,
    isNew: false,
    reviews: [],
    stock: 7,
  },
];
