import express from 'express';
import User from '../models/User.js';
import Order from '../models/Order.js';
import asyncHandler from 'express-async-handler';
import jwt from 'jsonwebtoken';
import protectRoute from '../middleware/authMiddleware.js';

const userRoutes = express.Router();

// generates a JWT (JSON Web Token) by signing the user ID with a secret key stored in the TOKEN_SECRET environment variable.
const genToken = (id) => {
  //CHANGE TO 24HR FOR PRODUCTION
  return jwt.sign({ id }, process.env.TOKEN_SECRET, { expiresIn: '60d' });
};

//handles the login process for users. It extracts the email and password from the request body, finds a user with the specified email using the User.findOne method, and verifies the password by calling the matchPassword method on the user object.
const loginUser = asyncHandler(async (req, res) => {
  const { email, password } = req.body;
  const user = await User.findOne({ email });

  //If the user exists and the password matches, it returns a JSON response that contains the user's ID, name, email, isAdmin status, and a JWT token generated by calling the genToken function with the user's ID.
  if (user && (await user.matchPasswords(password))) {
    res.json({
      _id: user._id,
      name: user.name,
      email: user.email,
      isAdmin: user.isAdmin,
      token: genToken(user._id),
      createdAt: user.createdAt,
    });

    //If the user does not exist or the password does not match, it sets the HTTP status code to 401 (Unauthorized) and throws an error with the message 'Invalid email or password'.
  } else {
    res.status(401).send('Invalid Email or Password');
    throw new Error('User not found.');
  }
});

const registerUser = asyncHandler(async (req, res) => {
  const { name, email, password } = req.body;

  const userExists = await User.findOne({ email });
  if (userExists) {
    res.status(400).send('We already have an account with that email address.');
  }

  const user = await User.create({
    name,
    email,
    password,
  });
  if (user) {
    res.status(201).json({
      _id: user._id,
      name: user.name,
      email: user.email,
      isAdmin: user.isAdmin,
      token: genToken(user._id),
    });
  } else {
    res.status(400).send('We could not register you.');
    throw new Error('Something went wrong. Please check your data and try again.');
  }
});

const updateUserProfile = asyncHandler(async (req, res) => {
  // it first retrieves a user from the database by calling User.findById function and passing in the id parameter from the req.params object. If the user is found, the function updates the user's name and email fields with values from the req.body object. If the req.body.password field is defined, the user's password is updated as well.
  const user = await User.findById(req.params.id);

  if (user) {
    user.name = req.body.name || user.name;
    user.email = req.body.email || user.email;
    if (req.body.password) {
      user.password = req.body.password;
    }
    //The updated user is then saved to the database by calling the user.save function.
    const updatedUser = await user.save();
    //unction sends a JSON response that includes the updated user's information, such as _id, name, email, isAdmin, token, and createdAt.
    res.json({
      _id: updatedUser._id,
      name: updatedUser.name,
      email: updatedUser.email,
      isAdmin: updatedUser.isAdmin,
      token: genToken(updatedUser._id),
      createdAt: updatedUser.createdAt,
    });
  } else {
    res.status(404);
    throw new Error('User not found.');
  }
});

const getUserOrders = asyncHandler(async (req, res) => {
  const orders = await Order.find({ user: req.params.id });
  if (orders) {
    res.json(orders);
  } else {
    res.status(404);
    throw new Error('No orders found');
  }
});

userRoutes.route('/login').post(loginUser);
userRoutes.route('/register').post(registerUser);
userRoutes.route('/profile/:id').put(protectRoute, updateUserProfile);
userRoutes.route('/:id').get(protectRoute, getUserOrders);

export default userRoutes;
